Set up associations, add classes: classrom book and rental
Berkay-akbas/School-Library pull request #3
Opened 2022-09-29 21:06 UTC by Berkay-akbas

## Hello Code Reviewer 👋 

# Changes
- New classes Classroom, book, rental are added.
- Created the associations between classes.

Thanks for the review!

2022-09-29 21:30 UTC, medaminedev66 requested changes
Hi @Berkay-akbas   😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- There are no linter errors
- You have a descriptive PR

## Required Changes ♻️
- [ ] The has-many / belongs-to relationships between Classroom and Student are still not completed. You should create a method in the Student class that serves as the 'belongs-to' side (a student belongs to a classroom). Check out this article with examples: [both-ways relationships](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships).
- [ ] Please ensure that the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental` is completed. You must still implement the `A person has many rentals` side.

_Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 21:30 UTC, medaminedev66 commented on book.rb
> +end
- [ ] According to the "A book has many rentals" relationship, a method for adding rentals should be present in the Book class. Check out the example in a previous lesson: [many-to-many relationship](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship)

2022-09-30 00:02 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @Berkay-akbas 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

## Highlights 🎯 
✔️ Descriptive PR
✔️ No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 00:02 UTC, codepantha commented on book.rb
> +  end
- [ ] There is no need to manually push the rental to the @rentals variable because it is already handled in the Rental class whenever a new instance of the Rental class is created

2022-09-30 07:21 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Berkay-akbas 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-01 12:36 UTC, merged